server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/students/**,/student-service/v3/api-docs
           
            - id: school-service
              uri: lb://school-service
              predicates:
                - Path=/api/schools/**,/school-service/v3/api-docs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Student Service
        url: /student-service/v3/api-docs
      - name: School Service
        url: /school-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG